### ISSUE TITLE
bootstrap always times out

### ISSUE THREAD

**Issue by ralyodio** [deoxxa/bittorrent-dht-byo#1]
var DHT = require('bittorrent-dht-byo');
	var dht = new DHT();

	var node = new DHT.Node({
	    host: "router.bittorrent.com",
	    port: 6881,
	});

	dht.bootstrap(node, function(err) {
	  if (err) {
	    console.error(err);
	  }

	  getPeers(null, handlePeers);
	});

	Error: timeout
	    at Error (native)
	    at Timeout._onTimeout (/home/user/tmp/spider/node_modules/bittorrent-dht-byo/lib/dht.js:169:19)
	    at tryOnTimeout (timers.js:232:11)
	    at Timer.listOnTimeout (timers.js:202:5)

**Comment by deoxxa** [comment]
Have you read the first part of the readme? By default there's no networking so it won't do anything. Maybe check out the example.js file.
